version: '3.8'

services:
  api:
    build: .
    container_name: search-engine-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - KMP_DUPLICATE_LIB_OK=TRUE
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    container_name: search-engine-ui
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - KMP_DUPLICATE_LIB_OK=TRUE
    command: streamlit run app/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
